### PR TITLE
JuliaBUGS support

### PR DESCRIPTION
**Pull request by miguelbiron**
@serenlee I've created this new PR with a more structured approach for giving support for JuliaBUGS models. It is based on Julia extension mechanisms, which allows us to keep precompilation times manageable for most users.
Now you can still keep working on your own PRs. But once you are comfortable with the code, we should migrate it to this PR.

Also, beyond the extension boilerplate code, I added a function that can automatically produce a prior model to use as default reference. It works by manipulating the underlying graph of the target, removing nodes related to observations. I think it is 80% there but needs testing.

### CODE REVIEW

**Comment by serenlee** [comment]
@miguelbiron Thanks!

I have also been interacting with the JuliaBUGS team. I will work on the JuliaBUGS target and push it to this PR branch.

**Comment by sunxd3** [comment]
Hi guys, thanks for working on this. Please just let me know if anything is needed, happy to make additions on the JuliaBUGS end!

**Comment by sunxd3** [comment]
https://github.com/TuringLang/JuliaBUGS.jl/pull/247

I am not taking the _contextual evaluation_ design for JuliaBUGS now because I felt the complexity is not worth it yet. So I just adde a function in the above PR. (at the cost of duplicated code)

The interface will very likely to change, but I'll make sure to update here once the potential happen.

**Comment by miguelbiron** [comment]
Ok, switched to the new interface and things seem to be proceeding smoothly! Thanks again @sunxd3 .

On a related note @sunxd3, I was thinking you could avoid having to maintain duplicated code by redefining `evaluate!!` to just call the tempered version with temp = 1.

**Comment by miguelbiron** [comment]
Need to make initialization more stable (currently depends on global RNG); might explain this sole fail

https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/12261789152/job/34209633693?pr=303#step:8:1128

**Comment by serenlee** [comment]
@alexandrebouchard 
Is the current version good to merge?

There is a to-do list 
- @miguelbiron mentioned that running MPI has some issues.
- I got an error of this #296 in extreme cases, but other than it works well.
- Gibbs Explorer will keep interacting with the JuliaBUGS team about this.

**Comment by miguelbiron** [comment]
@serenlee the MPI issue is fixed now. There was an issue with the way I was creating the private models for the replicas, which was affecting the MPI stuff downstream.

**Comment by miguelbiron** [comment]
The parallelism invariance check (`checked_round` input param) is the one part not working, but just because the equality check of BUGSModels is non-trivial.

**Comment by miguelbiron** [comment]
Pushed a fix that should close #296

**Comment by miguelbiron** [comment]
Ok everything in [@serenlee 's list](https://github.com/Julia-Tempering/Pigeons.jl/pull/303#issuecomment-2547306248) has been fixed (except for the Gibbs sampler which is not our problem). I'll merge this now.

**Pull request merged**
