### PR TITLE
Start move to extensions

### PR DESCRIPTION
**Pull request by ptiede**
This pull request will attempt to move the Turing and BridgeStan intefaces to the new Julia extensions.

**Work in progress**

### CODE REVIEW

**Comment by miguelbiron** [comment]
hey Paul -- just a heads up the 8 schools example is already updated to the new syntax in the main branch. You might need to pull those changes

**Comment by ptiede** [comment]
@miguelbiron thanks! I just saw that and rebased off main, so I think I am up to date? 
I think other than some stan stuff the test are passing locally. I will do a little write-up shortly to explain what I did and some open questions that I need some feedback on.

**Comment by miguelbiron** [comment]
@ptiede yes I think you're good now. Very excited for this PR!

**Comment by ptiede** [comment]
Ok, I think that does it. All the tests pass locally. There is an issue with the docs, but this points to a slightly larger issue that I'll discuss below.

The goal of this PR was to move some of Pigeon's dependencies to extensions. The reason for this is mostly for load times and partially to prevent Pigeons from having too many direct dependencies. To do this, I separated `BridgeStan` and `DynamicPPL` into `PigeonsBridgeStanExt` and `PigeonsDynamicPPLExt`. These are separate folders that live in the `ext` folder. Each folder is split into three parts:

 1. The main extension file, e.g., `PigeonsBridgeStanExt.jl` which imports the various packages and includes the other files
 2. `interface.jl`  that defines constructors for things like `StanLogPotential` and other functions that satisfy the Pigeons interface
 3. `state.jl` that handles things like updating the state of the sampler with the various constructs defined
 4. (optional) `toy_examples.jl` a file that contains all the toy examples we use in testing and the docs

Now there are some quirks in this implementation that we should discuss before merging this PR. The root cause of the quirks is that the Julia extension system does not allow you to export symbols defined in the extension module to the global scope. So, for instance, since I define `StanState` in the BridgeStan extension, I cannot access this state directly unless I do some chicanery
```julia
PigeonsBridgeStanExt = Base.get_extension(Pigeons, :PigeonsBridgeStanExt)
PigeonsBridgeStanExt.StanState
```
which is considered bad since `get_extension` is currently an internal Julia method. This means that I could not remove all references of BridgeStan and DynamicPPL from Pigeons. (you can see what still remains in `src/targets/StanLogPotential.jl` and `src/targets/TuringLogPotential.jl`).

The main things in each of these files are
  1. `LogPotential` for each package, e.g., `TuringLogPotential`
  2. Some helping methods that we may want to expose to the user
  3. functions that provide hooks for the toy examples, e.g., `toy_turing_target`

Going through this made me think we can partially solve 1 and 3 with some (hopefully) minor code refactoring. 

Starting with item 3, I would like to know if we should include these toy examples in the Pigeons module. I feel these should live either in examples or even in tests. These additional functions mean we have to support them directly, and if we wanted to remove any of them, we would need to do a breaking release of Pigeons since, at least to my reading, some of them are part of the public API (we use them in the docs). 

Moving to item 1. I think this could be solved by adding an additional abstraction layer to `Inputs` and specifically target. Right now we have a slightly annoying interface to `target` where a user first has to define a Turing model and then wrap it in a `TuringLogDensity`. Consider, for instance, if we instead have an informal interface called `create_target` where we could dispatch off the type of target to create these internal representations automatically.

The implementation would look something like

```

create_target(f::Function) = f
create_target(m::DynamicPPL.Model) = TuringLogPotential(m)
create_target(m::Distributions.Distribution) = DistributionLogPotential(m)

function Inputs(
            target::T,
            seed::Int, n_rounds::Int,
            n_chains::Int, n_chains_variational::Int,
            reference::R, variational::V, checkpoint::Bool,
            record::Vector, checked_round::Int, multithreaded::Bool,
            explorer::E, show_report::Bool, trace_type::Symbol) where {T, R, V, E}

        pigeons_target = create_target(target)
        return Inputs{T,V,E,R}(pigeons_target, seed, n_rounds, n_chains, n_chains_variational, reference, variational,
                               checkpoint, record, checked_round, multithreaded, explorer, show_report, trace_type)
end
```

in this case, I could move `TuringLogPotential` to the extension package, although for BridgeStan, that doesn't seem to be the case since the struct is more complicated. Additionally, the user wouldn't have to worry about wrapping their construct in specific Pigeons wrappers anymore. 

Some other miscellaneous things I noticed. We seem to be doing a lot of type piracy in Pigeons. Most of it seems to be focussed on the use of `Base.:(==)`, which we have overloaded for things like `DynamicPPL.TypedVarInfo` and `Iterators`. Since we don't own either of these constructs, we should remove this from the code.  This is especially true for Iterators which is a part of the Julia standard library. I would rather have us switch to using `recursive_equal` for every check, which should fix this issue. 

Finally, the remaining issues with the docs are:

 1. `toy_stan_target` and `toy_turing_unid_target` are not included in the docs. This only happens on 1.8 so it seems like some annoying thing with Requires
 2. `StanState` reference not found. Again this is because `StanState` is in the extension package and isn't being exported. I can move this to `Pigeons` proper, but I kind of consider `StanState` as part of the internal detail of the code since most users will just want the constrained values.

**Comment by alexandrebouchard** [comment]
Thank you so much Paul, this is really awesome! I will have to digest some of the points but here are some quick first thoughts on a subset of the points (will do a follow up on the others):

- One idea: for the StanState stuff, we could always have an abstract type called StanState, and define StanStateImpl in ext? And similarly for the other ones..
- for the `create_target` dispatch idea, that was indeed what I was hoping to do initially. One limitation is that this would not straightforwardly work with Stan targets (in short, BridgeStan.StanModel does not retain the information necessary for our custom serialization (https://github.com/Julia-Tempering/Pigeons.jl/blob/3a30ebf1805dc8e6634bbbadad98b055defdfb4c/src/targets/StanLogPotential.jl#L43) that serialization is required for the distributed stuff to work. Also slightly reluctant to break the API but not completely closed to it either.
- for the toy_target, the rationale for that is when doing demos having a few of those can reduce friction in certain circumstances. For the same reason e.g. some R packages include toy datasets which the first time I saw that I thought it was the dummest idea but then it saved my ass a few times in teaching context
- type piracy for `==`: yes I agree this is something we should improve. These acts of piracy are workarounds for cases where the default == is weird, they are kind of necessary for the correctness checks. It's one of these cases where the typical strategy to define our own my_equal would involve a ton of additional code at least in the alternatives I toyed with (in a nutshell, even if we default my_equal to ==, when an == outside of control recurses, it invokes ==, not my_equal...). Suggestions are welcome!
- other type piracy I would be interested to hear about too!
- to be continued...

**Comment by ptiede** [comment]
Looks like everything passed! Should we merge this @miguelbiron @alexandrebouchard

**Comment by alexandrebouchard** [comment]
Looks great! Thank you so much Paul. Just added a couple of tests, to ensure both the 1.9 and Require.jl routes work as expected. After that I am in favour of merging!

**Comment by alexandrebouchard** [comment]
I think the test failed because with Require maybe the order of the using statements matter. Maybe the documentation for Stan targets and Turing targets should mention that?

**Comment by ptiede** [comment]
I can add a warning to the docs but it looks like the failures are actually due to a difference in how errors are printed in 1.8 v.s. 1.9 and later. In 1.8 this is printed
```julia
UndefVarError: toy_mvn_target not defined
```

and in 1.9 it is
```julia
UndefVarError: `toy_mvn_target` not defined
```

**Comment by ptiede** [comment]
Ok the version switching seemed to work in the tests. I'll add the warning to docs later tonight and then we can get this merged!

**Comment by alexandrebouchard** [comment]
Sorry I had misinterpreted the error! Then if I understand correctly it seems that even with Require the order does not matter, in which case no need to update the doc. Good to go for merging in my opinion.

**Comment by alexandrebouchard** [comment]
Awesome!!!

**Pull request merged**
