### PR TITLE
Test that the variational ref is being used

### PR DESCRIPTION
**Pull request by alexandrebouchard**

### CODE REVIEW

**Comment by alexandrebouchard** [comment]
Hey @nikola-sur I wonder if maybe the variational reference is not being used in the test in the main branch?

**Comment by alexandrebouchard** [comment]
Happy to help, but I won't touch anything until we touch base (I know you are working on another variational branch if I recall correctly)

**Comment by nikola-sur** [comment]
I'll check it out right now

**Comment by nikola-sur** [comment]
One (semi-related) question: even when I don't use the variational reference but just n_chains = 10, n_chains_var_reference = 0, the reports output for the Turing example is not deterministic for a given seed? Didn't we come across this issue with Turing changing the seed somewhere else before?

**Comment by nikola-sur** [comment]
@alexandrebouchard For the question you raised, I think you were accessing the wrong shared element. It is `pt.shared.var_reference`.

**Pull request merged**
