### PR TITLE
Fix `==` piracy

### LINKED ISSUE #163: Fix type piracy of ==

### PR DESCRIPTION
**Pull request by miguelbiron**
Fixes #163

### CODE REVIEW

**Comment by alexandrebouchard** [comment]
Thanks Miguel! I would just add a `@test_throws` on an intentionally faulty/non-reproducible test example. 

Also just noticed that the DynamicPPL implementation does not actually check equality, just length of metadata. Can we fix that at the same time?

Might be good to add doc string and mention the `recursive_equal` function in https://pigeons.run/dev/correctness/ - in its comment maybe point to the StanBridgeExtension for some examples of how it gets used.

**Comment by alexandrebouchard** [comment]
Idea: for the DynamicPPL implementation, use `DynamicPPL.getall` instead?

**Comment by alexandrebouchard** [comment]
this puts all the variables (discrete and continuous) into one big vector

**Comment by alexandrebouchard** [comment]
... and maybe check too `variable_names()`

**Comment by miguelbiron** [comment]
Thanks for the feedback @alexandrebouchard ! I'll give the DynamicPPL check a try

**Comment by miguelbiron** [comment]
It looks like our implementation already checks every value right?
https://github.com/Julia-Tempering/Pigeons.jl/blob/3c4ca7e3fee011433fe6d20fb232af6806e6b16b/ext/PigeonsDynamicPPLExt/state.jl#L83-L87

**Comment by alexandrebouchard** [comment]
Sorry, you are right, I was just looking at the diff and missed the other lines!

**Comment by miguelbiron** [comment]
Something weird happened with symlinks on [this run](https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6787170971/job/18449385235?pr=175) inside an Ubuntu machine; see the lines

https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6787170971/job/18449385235?pr=175#step:8:3812

and

https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6787170971/job/18449385235?pr=175#step:8:4027

**Comment by miguelbiron** [comment]
Still happening. Any idea why @alexandrebouchard ? Can't reproduce locally. It happened on these two runs

[Julia 1.9 - ubuntu-latest - x64](https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6788510405/job/18453695153?pr=175#logs)
- https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6788510405/job/18453695153?pr=175#step:8:3857
- https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6788510405/job/18453695153?pr=175#step:8:4010

[Julia 1.8 - ubuntu-latest - x64](https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6788510405/job/18453693973?pr=175#logs)
- https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6788510405/job/18453693973?pr=175#step:8:3922

Interestingly, the remaining Ubuntu run is unaffected: [Julia 1.8 - ubuntu-latest - OpenMPI_jll](https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/6788510405/job/18453694860?pr=175#logs)

**Comment by alexandrebouchard** [comment]
These tests were introduced relatively recently, looks like there is a race condition hidden in the checkpoint resume code. Annoyingly it's not even clear from the output which test encounters that. 

I am toying with the idea of removing all checkpointing functionalities as it is complex and does not seem that helpful anyways: doing one more rounds from scratch vs saved checkpoint is just a factor 2 saving. Thoughts?

**Comment by alexandrebouchard** [comment]
Just did a quick check and I don't see an immediate explanation: `safelink()` for inputs.jls is only occurring in `checkpoint_symlinks!` which has only 2 calls. The only one that should be under MPI is in `PT()` in checkpoint.jl but it is surrounded by a `only_one_process(result) do ...` construct. So I don't understand why there would be a race condition there.

**Comment by alexandrebouchard** [comment]
Thinking about it, I see now in `checkpoint_symlinks!()` I have created a `same_inputs` arg, I think the problem must be that one caller does not set it correctly! So pretty minor potentially...

**Comment by miguelbiron** [comment]
Oh that's good to hear. Let's go ahead and merge this PR and I'll make an issue with your findings for dealing with it later, ok?

**Comment by alexandrebouchard** [comment]
Sounds good!

**Pull request merged**
