### PR TITLE
Mix: a mixture of explorers

### PR DESCRIPTION
**Pull request by miguelbiron**
Lets use mixtures of explorers via the syntax 
```julia
    mixed_AM = Mix(
        AutoMALA(preconditioner=Pigeons.IdentityPreconditioner()),
        AutoMALA(preconditioner=Pigeons.MixDiagonalPreconditioner()),
        AutoMALA(preconditioner=Pigeons.DiagonalPreconditioner())
    )
```

Edit 2: got the vararg constructor!

### CODE REVIEW

**Comment by miguelbiron** [comment]
I added Mix to the parallelism invariance test array. As I told @alexandrebouchard , the test suite failed on my pc but on the bare AutoMALA explorer (with a julia target, see trace below). Hopefully this is just something wrong with my setup, so :crossed_fingers: that CI passes here.

```julia
(explorer, target) = (AutoMALA{Nothing, Pigeons.MixDiagonalPreconditioner}(3, 0.35, :ForwardDiff, 1.0, Pigeons.MixDiagonalPreconditioner(), nothing), Pigeons.ScaledPrecisionNormalPath(1.0, 10.0, 1))
is_stan = target isa Pigeons.StanLogPotential = false
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
Entangler initialized 2 MPI processes; 2 threads per process
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
  scans     restarts      Λ      log(Z₁/Z₀)   min(α)     mean(α)    max|ρ|     mean|ρ|    min(αₑ)   mean(αₑ) 
────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ──────────
        2          0       1.99      -2.07      0.231      0.779          1          1          0      0.606 
        4          0      0.505     -0.758      0.685      0.944      0.998      0.555      0.521      0.651 
        8          0      0.928     -0.959      0.748      0.897       0.92      0.426      0.486       0.62 
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
  scans     restarts      Λ      log(Z₁/Z₀)   min(α)     mean(α)    max|ρ|     mean|ρ|    min(αₑ)   mean(αₑ) 
────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ──────────
        2          0       1.99      -2.07      0.231      0.779          1          1          0      0.606 
        4          0      0.505     -0.758      0.685      0.944      0.998      0.555      0.521      0.651 
        8          0      0.928     -0.959      0.748      0.897       0.92      0.426      0.486       0.62 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
       16          1      0.944      -1.26       0.83      0.895      0.973      0.336      0.509      0.639 
       32          5      0.711      -1.37      0.823      0.921      0.404      0.183      0.564      0.628 
       64         17      0.665      -1.07      0.893      0.926       0.62      0.385      0.611      0.655 
      128         31      0.785      -1.21      0.857      0.913      0.379      0.202      0.616      0.661 
      256         68      0.702      -1.15      0.891      0.922      0.495      0.244      0.604      0.648 
      512        141      0.783      -1.22      0.893      0.913      0.424      0.227      0.611      0.659 

julia:16042 terminated with signal 11 at PC=7f84ab290839 SP=7f8458f77970.  Backtrace:
/home/mbiron/opt/julia/usr/bin/../lib/libjulia-internal.so.1(_jl_mutex_unlock+0x59)[0x7f84ab290839]
/home/mbiron/opt/julia/usr/bin/../lib/libjulia-internal.so.1(ijl_process_events+0xb4)[0x7f84ab27d3f4]
/home/mbiron/opt/julia/usr/bin/../lib/libjulia-internal.so.1(ijl_task_get_next+0xf8)[0x7f84ab290e08]
/home/mbiron/opt/julia/usr/lib/julia/sys.so(+0x4c4755)[0x7f84970c4755]
/home/mbiron/opt/julia/usr/lib/julia/sys.so(+0x7d375b)[0x7f84973d375b]
/home/mbiron/opt/julia/usr/lib/julia/sys.so(+0x8cddf2)[0x7f84974cddf2]
/home/mbiron/opt/julia/usr/lib/julia/sys.so(+0x8ce0cc)[0x7f84974ce0cc]
/home/mbiron/opt/julia/usr/bin/../lib/libjulia-internal.so.1(+0x6376e)[0x7f84ab26376e]
/home/mbiron/opt/julia/usr/bin/../lib/libjulia-internal.so.1(+0x63905)[0x7f84ab263905]
Parallelism Invariance: Error During Test at /home/mbiron/projects/Pigeons.jl/test/test_parallelism_invariance.jl:4
  Got exception outside of a @test
  failed process: Process(`mpiexec -n 2 /home/mbiron/opt/julia/usr/bin/julia -Cnative -J/home/mbiron/opt/julia/usr/lib/julia/sys.so -g1 --startup-file=no --banner=no --project=/home/mbiron/projects/Pigeons.jl/test --threads=2 /home/mbiron/projects/Pigeons.jl/results/all/2023-10-20-12-10-10-SCVBLAc7/.launch_script.jl`, ProcessExited(1)) [1]
  
  Stacktrace:
    [1] pipeline_error
      @ ./process.jl:565 [inlined]
    [2] run(::Cmd; wait::Bool)
      @ Base ./process.jl:480
    [3] run
      @ ./process.jl:477 [inlined]
    [4] #92
      @ ~/projects/Pigeons.jl/src/submission/ChildProcess.jl:78 [inlined]
    [5] #mpiexec#2
      @ ~/.julia/packages/MPIPreferences/43Ix2/src/system.jl:11 [inlined]
    [6] mpiexec
      @ ~/.julia/packages/MPIPreferences/43Ix2/src/system.jl:11 [inlined]
    [7] pigeons(pt_arguments::Inputs{Pigeons.ScaledPrecisionNormalPath, Nothing, AutoMALA{Nothing, Pigeons.MixDiagonalPreconditioner}, Nothing}, new_process::ChildProcess)
      @ Pigeons ~/projects/Pigeons.jl/src/submission/ChildProcess.jl:75
    [8] #pigeons#157
      @ ~/projects/Pigeons.jl/src/api.jl:16 [inlined]
    [9] macro expansion
      @ ~/projects/Pigeons.jl/test/test_parallelism_invariance.jl:24 [inlined]
   [10] macro expansion
      @ ~/opt/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
   [11] top-level scope
      @ ~/projects/Pigeons.jl/test/test_parallelism_invariance.jl:5
   [12] include(fname::String)
      @ Base.MainInclude ./client.jl:478
   [13] top-level scope
      @ ~/projects/Pigeons.jl/test/temp.jl:2
   [14] eval
      @ ./boot.jl:370 [inlined]
   [15] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
      @ Base ./loading.jl:1903
   [16] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ Base ./essentials.jl:819
   [17] invokelatest(::Any, ::Any, ::Vararg{Any})
      @ Base ./essentials.jl:816
   [18] inlineeval(m::Module, code::String, code_line::Int64, code_column::Int64, file::String; softscope::Bool)
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/eval.jl:261
   [19] (::VSCodeServer.var"#67#72"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/eval.jl:181
   [20] withpath(f::VSCodeServer.var"#67#72"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams}, path::String)
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/repl.jl:274
   [21] (::VSCodeServer.var"#66#71"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/eval.jl:179
   [22] hideprompt(f::VSCodeServer.var"#66#71"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/repl.jl:38
   [23] (::VSCodeServer.var"#65#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/eval.jl:150
   [24] with_logstate(f::Function, logstate::Any)
      @ Base.CoreLogging ./logging.jl:514
   [25] with_logger
      @ ./logging.jl:626 [inlined]
   [26] (::VSCodeServer.var"#64#69"{VSCodeServer.ReplRunCodeRequestParams})()
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/eval.jl:253
   [27] #invokelatest#2
      @ ./essentials.jl:819 [inlined]
   [28] invokelatest(::Any)
      @ Base ./essentials.jl:816
   [29] macro expansion
      @ ~/.vscode/extensions/julialang.language-julia-1.54.2/scripts/packages/VSCodeServer/src/eval.jl:34 [inlined]
   [30] (::VSCodeServer.var"#62#63")()
      @ VSCodeServer ./task.jl:514
Test Summary:          | Error  Total     Time
Parallelism Invariance |     1      1  2m56.9s
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at
```

**Comment by nikola-sur** [comment]
Nice! Looks good to me. I suppose there are multiple ways to go about this:
- Tuple of explorers + vector of probabilities (current implementation)
- Tuple of explorers + tuple of probabilities?
- Vector + vector?
- Tuple of tuples (each tuple is one explorer + one probability)

I am fine with the current way.

**Comment by miguelbiron** [comment]
Vector of explorers is not efficient because the eltype cannot be concrete. We talked about this in the meeting. Tuple seems the way to go

**Comment by miguelbiron** [comment]
Now, I got a parallelism invariance error. @alexandrebouchard might it be related to me using a Distributions as field of the explorer? Maybe I need to add a `==` method?
```julia
julia> include("activate_test_env.jl")
       include("test_parallelism_invariance.jl")
  Activating project at `~/projects/Pigeons.jl/test`
   Resolving package versions...
  No Changes to `~/projects/Pigeons.jl/test/Project.toml`
  No Changes to `~/projects/Pigeons.jl/test/Manifest.toml`
[ Info: Precompiling Pigeons [0eb8d820-af6a-4919-95ae-11206f830c31]
┌ Info: next time you call `test` from the parent project 
│ to run all tests, you may get an error message 
│ about "can not merge projects", if so, simply delete 
└ the generated file "test/Manifest.toml"
┌ Warning: At the moment, for StanLogPotential please use a single thread 
│ (but several MPI processes can still be used).
└ @ Pigeons ~/projects/Pigeons.jl/src/targets/StanLogPotential.jl:35
(explorer, target) = (Mix{...}((AutoMALA{Nothing, Pigeons.IdentityPreconditioner}(3, 0.35, :ForwardDiff, 1.0, Pigeons.IdentityPreconditioner(), nothing), AutoMALA{Nothing, Pigeons.MixDiagonalPreconditioner}(3, 0.35, :ForwardDiff, 1.0, Pigeons.MixDiagonalPreconditioner(), nothing), AutoMALA{Nothing, Pigeons.DiagonalPreconditioner}(3, 0.35, :ForwardDiff, 1.0, Pigeons.DiagonalPreconditioner(), nothing)), Categorical{Float64, Vector{Float64}}(support=Base.OneTo(3), p=[0.3333333333333333, 0.3333333333333333, 0.3333333333333333])), Pigeons.ScaledPrecisionNormalPath(1.0, 10.0, 1))
is_stan = target isa Pigeons.StanLogPotential = false
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
Entangler initialized 2 MPI processes; 2 threads per process
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
  scans     restarts      Λ      log(Z₁/Z₀)   min(α)     mean(α)    max|ρ|     mean|ρ|    min(αₑ)   mean(αₑ) 
────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ──────────
        2          0      0.691      -1.59      0.652      0.923          1          1      0.411      0.748 
        4          0       1.14      -1.36      0.413      0.874      0.942      0.595      0.235      0.582 
        8          0      0.734     -0.729      0.687      0.918      0.791      0.357       0.43      0.649 
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
┌ Info: Neither traces, disk, nor online recorders included. 
│    You may not have access to your samples (unless you are using a custom recorder, or maybe you just want log(Z)).
└    To add recorders, use e.g. pigeons(target = ..., record = [traces; record_default()])
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
  scans     restarts      Λ      log(Z₁/Z₀)   min(α)     mean(α)    max|ρ|     mean|ρ|    min(αₑ)   mean(αₑ) 
────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ──────────
        2          0      0.691      -1.59      0.652      0.923          1          1      0.411      0.748 
        4          0       1.14      -1.36      0.413      0.874      0.942      0.595      0.235      0.582 
        8          0      0.734     -0.729      0.687      0.918      0.791      0.357       0.43      0.649 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
ERROR: LoadError: detected non-reproducibility, to investigate, type in the REPL:
─────────────────────────────────
 using Serialization
 first  = deserialize("/home/mbiron/projects/Pigeons.jl/results/all/2023-10-20-12-33-53-D6qjY5kM/round=3/checkpoint/shared.jls");
 second = deserialize("/home/mbiron/projects/Pigeons.jl/results/all/2023-10-20-12-34-24-PVWkAweX/round=3/checkpoint/shared.jls");
─────────────────────────────────
If you are using custom stuct, either mutable or containing 
mutables, you may just need to add custom ==, see 
src/pt/checks.jl.
```

**Comment by miguelbiron** [comment]
The problem for the parallelism invariance error is that I needed to extend `==` for Mix
```
Base.:(==)(a::Mix, b::Mix) = recursive_equal(a, b)    
```

**Pull request merged**
